config/routes.rb
Rails.application.routes.draw do
  resources :e_comments
  resources :news_comments
  resources :event_posts
  resources :news_posts
  resources :users
  resources :divisions
  resources :organizations, only: %i[ index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/me', to: 'users#me'

  # sessions
  post '/login', to: 'sessions#login'
  delete '/logout', to: 'sessions#logout'

  # filters
  get '/news_date', to: 'news_posts#date'

  # this will allow for the deployment to us react
  get '*path',
      to: 'fallback#index',
      constraints: ->(req) { !req.xhr? && req.format.html? }
end

app/models/e_comment.rb
class EComment < ApplicationRecord
  belongs_to :user
  belongs_to :event_post
end

app/controllers/e_comments_controller.rb
class ECommentsController < ApplicationController
  before_action :set_e_comment, only: %i[ show edit update destroy ]

  # GET /e_comments or /e_comments.json
  def index
    @e_comments = EComment.all
    render json: @e_comments
  end

  # GET /e_comments/1 or /e_comments/1.json
  def show
  end

  # GET /e_comments/new
  def new
    @e_comment = EComment.new
  end

  # GET /e_comments/1/edit
  def edit
  end

  # POST /e_comments or /e_comments.json
  def create
    comment = EComment.create(e_comment_params)
       
    render json: comment
  end

  # PATCH/PUT /e_comments/1 or /e_comments/1.json
  def update
    respond_to do |format|
      if @e_comment.update(e_comment_params)
        format.html { redirect_to e_comment_url(@e_comment), notice: "E comment was successfully updated." }
        format.json { render :show, status: :ok, location: @e_comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @e_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /e_comments/1 or /e_comments/1.json
  def destroy
    @e_comment.destroy

    respond_to do |format|
      format.html { redirect_to e_comments_url, notice: "E comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_e_comment
      @e_comment = EComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def e_comment_params
      params.require(:e_comment).permit(:user_id, :event_post_id, :comment)
    end
end

app/helpers/e_comments_helper.rb
module ECommentsHelper
end

app/views/e_comments/_form.html.erb
<%= form_with(model: e_comment) do |form| %>
  <% if e_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(e_comment.errors.count, "error") %> prohibited this e_comment from being saved:</h2>

      <ul>
        <% e_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :event_post_id %>
    <%= form.text_field :event_post_id %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/e_comments/edit.html.erb
<h1>Editing E Comment</h1>

<%= render 'form', e_comment: @e_comment %>

<%= link_to 'Show', @e_comment %> |
<%= link_to 'Back', e_comments_path %>

app/views/e_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>E Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event post</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @e_comments.each do |e_comment| %>
      <tr>
        <td><%= e_comment.user_id %></td>
        <td><%= e_comment.event_post_id %></td>
        <td><%= e_comment.comment %></td>
        <td><%= link_to 'Show', e_comment %></td>
        <td><%= link_to 'Edit', edit_e_comment_path(e_comment) %></td>
        <td><%= link_to 'Destroy', e_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New E Comment', new_e_comment_path %>

app/views/e_comments/new.html.erb
<h1>New E Comment</h1>

<%= render 'form', e_comment: @e_comment %>

<%= link_to 'Back', e_comments_path %>

app/views/e_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @e_comment.user_id %>
</p>

<p>
  <strong>Event post:</strong>
  <%= @e_comment.event_post_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @e_comment.comment %>
</p>

<%= link_to 'Edit', edit_e_comment_path(@e_comment) %> |
<%= link_to 'Back', e_comments_path %>