config/routes.rb
Rails.application.routes.draw do
  resources :e_comments
  resources :news_comments
  resources :event_posts
  resources :news_posts
  resources :users
  resources :divisions
  resources :organizations, only: %i[ index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/me', to: 'users#me'

  # sessions
  post '/login', to: 'sessions#login'
  delete '/logout', to: 'sessions#logout'

  # filters
  get '/news_date', to: 'news_posts#date'

  # this will allow for the deployment to us react
  get '*path',
      to: 'fallback#index',
      constraints: ->(req) { !req.xhr? && req.format.html? }
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :organization
  has_many :users
  has_many :news_posts, through: :users
  has_many :event_posts, through: :users
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :set_division, only: %i[show edit update destroy]

  # GET /divisions or /divisions.json
  def index
    @divisions = Division.all
    render json: @divisions
  end

  # GET /divisions/1 or /divisions/1.json
  def show; end

  # GET /divisions/new
  def new
    @division = Division.new
  end

  # GET /divisions/1/edit
  def edit; end

  # POST /divisions or /divisions.json
  def create
    @division = Division.new(division_params)

    respond_to do |format|
      if @division.save
        format.html do
          redirect_to division_url(@division),
                      notice: 'Division was successfully created.'
        end
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @division.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /divisions/1 or /divisions/1.json
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html do
          redirect_to division_url(@division),
                      notice: 'Division was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @division.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /divisions/1 or /divisions/1.json
  def destroy
    @division.destroy

    respond_to do |format|
      format.html do
        redirect_to divisions_url,
                    notice: 'Division was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_division
    @division = Division.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def division_params
    params.require(:division).permit(:name, :active, :organization_id)
  end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.erb
<%= form_with(model: division) do |form| %>
  <% if division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
        <% division.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :organization_id %>
    <%= form.text_field :organization_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

app/views/divisions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Divisions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @divisions.each do |division| %>
      <tr>
        <td><%= division.name %></td>
        <td><%= division.active %></td>
        <td><%= division.organization_id %></td>
        <td><%= link_to 'Show', division %></td>
        <td><%= link_to 'Edit', edit_division_path(division) %></td>
        <td><%= link_to 'Destroy', division, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Division', new_division_path %>

app/views/divisions/new.html.erb
<h1>New Division</h1>

<%= render 'form', division: @division %>

<%= link_to 'Back', divisions_path %>

app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @division.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @division.active %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @division.organization_id %>
</p>

<%= link_to 'Edit', edit_division_path(@division) %> |
<%= link_to 'Back', divisions_path %>