config/routes.rb
Rails.application.routes.draw do
  resources :e_comments
  resources :news_comments
  resources :event_posts
  resources :news_posts
  resources :users
  resources :divisions
  resources :organizations, only: %i[ index]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/me', to: 'users#me'

  # sessions
  post '/login', to: 'sessions#login'
  delete '/logout', to: 'sessions#logout'

  # filters
  get '/news_date', to: 'news_posts#date'

  # this will allow for the deployment to us react
  get '*path',
      to: 'fallback#index',
      constraints: ->(req) { !req.xhr? && req.format.html? }
end

app/models/event_post.rb
class EventPost < ApplicationRecord
  belongs_to :user
  belongs_to :division
  has_one_attached :avatar
  has_many :e_comments
end

app/controllers/event_posts_controller.rb
class EventPostsController < ApplicationController
  before_action :set_event_post, only: %i[ show edit update destroy ]

  # GET /event_posts or /event_posts.json
    # comment out render json below to see the erb
  def index
    @event_posts = EventPost.all.order(:event_date)
  
   render json: @event_posts
  end

  # GET /event_posts/1 or /event_posts/1.json
  def show

    # render json: @event_post
    event = EventPost.find_by(id:params[:id])
    render json:event
    # (:include => :e_comments)
  end

  # GET /event_posts/new
  def new
    @event_post = EventPost.new
  end

  # GET /event_posts/1/edit
  def edit
  end

  # POST /event_posts or /event_posts.json
  def create
    @event_post = EventPost.new(event_post_params)

    respond_to do |format|
      if @event_post.save
        format.html { redirect_to event_post_url(@event_post), notice: "Event post was successfully created." }
        format.json { render :show, status: :created, location: @event_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event_post.errors, status: :unprocessable_entity }
      end
    end
  end
  # delete this

  # PATCH/PUT /event_posts/1 or /event_posts/1.json
  def update
    @event_post.update(event_post_params)
    render json: @event_post
    # respond_to do |format|
    #   if @event_post.update(event_post_params)
    #     format.html { redirect_to event_post_url(@event_post), notice: "Event post was successfully updated." }
    #     format.json { render :show, status: :ok, location: @event_post }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @event_post.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /event_posts/1 or /event_posts/1.json
  def destroy
    @event_post.destroy

    respond_to do |format|
      format.html { redirect_to event_posts_url, notice: "Event post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_post
      @event_post = EventPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_post_params
      params.require(:event_post).permit(:date_created, :title, :content, :event_date, :event_time, :event_allday, :event_location, :division_target, :avatar, :topic, :claps, :clicks, :user_id, :division_id)
    end
end

app/helpers/event_posts_helper.rb
module EventPostsHelper
end

app/views/event_posts/_form.html.erb
<%= form_with(model: event_post) do |form| %>
  <% if event_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_post.errors.count, "error") %> prohibited this event_post from being saved:</h2>

      <ul>
        <% event_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_created %>
    <%= form.text_field :date_created %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :event_date %>
    <%= form.date_select :event_date %>
  </div>

  <div class="field">
    <%= form.label :event_time %>
    <%= form.time_select :event_time %>
  </div>

  <div class="field">
    <%= form.label :event_allday %>
    <%= form.check_box :event_allday %>
  </div>

  <div class="field">
    <%= form.label :event_location %>
    <%= form.text_field :event_location %>
  </div>

  <div class="field">
    <%= form.label :division_target %>
    <%= form.text_field :division_target %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="field">
    <%= form.label :topic %>
    <%= form.text_field :topic %>
  </div>

  <div class="field">
    <%= form.label :claps %>
    <%= form.number_field :claps %>
  </div>

  <div class="field">
    <%= form.label :clicks %>
    <%= form.number_field :clicks %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :division_id %>
    <%= form.text_field :division_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_posts/edit.html.erb
<h1>Editing Event Post</h1>

<%= render 'form', event_post: @event_post %>

<%= link_to 'Show', @event_post %> |
<%= link_to 'Back', event_posts_path %>

app/views/event_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Posts</h1>

<table>
  <thead>
    <tr>
      <th>Date created</th>
      <th>Title</th>
      <th>Content</th>
      <th>Event date</th>
      <th>Event time</th>
      <th>Event allday</th>
      <th>Event location</th>
      <th>Division target</th>
      <th>Avatar</th>
      <th>Topic</th>
      <th>Claps</th>
      <th>Clicks</th>
      <th>User</th>
      <th>Division</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_posts.each do |event_post| %>
      <tr>
        <td><%= event_post.date_created %></td>
        <td><%= event_post.title %></td>
        <td><%= event_post.content %></td>
        <td><%= event_post.event_date %></td>
        <td><%= event_post.event_time %></td>
        <td><%= event_post.event_allday %></td>
        <td><%= event_post.event_location %></td>
        <td><%= event_post.division_target %></td>
        <td><%= event_post.avatar %></td>
        <td><%= event_post.topic %></td>
        <td><%= event_post.claps %></td>
        <td><%= event_post.clicks %></td>
        <td><%= event_post.user_id %></td>
        <td><%= event_post.division_id %></td>
        <td><%= link_to 'Show', event_post %></td>
        <td><%= link_to 'Edit', edit_event_post_path(event_post) %></td>
        <td><%= link_to 'Destroy', event_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Post', new_event_post_path %>

app/views/event_posts/new.html.erb
<h1>New Event Post</h1>

<%= render 'form', event_post: @event_post %>

<%= link_to 'Back', event_posts_path %>

app/views/event_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date created:</strong>
  <%= @event_post.date_created %>
</p>

<p>
  <strong>Title:</strong>
  <%= @event_post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @event_post.content %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event_post.event_date %>
</p>

<p>
  <strong>Event time:</strong>
  <%= @event_post.event_time %>
</p>

<p>
  <strong>Event allday:</strong>
  <%= @event_post.event_allday %>
</p>

<p>
  <strong>Event location:</strong>
  <%= @event_post.event_location %>
</p>

<p>
  <strong>Division target:</strong>
  <%= @event_post.division_target %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= link_to @event_post.avatar.filename, @event_post.avatar if @event_post.avatar.attached? %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @event_post.topic %>
</p>

<p>
  <strong>Claps:</strong>
  <%= @event_post.claps %>
</p>

<p>
  <strong>Clicks:</strong>
  <%= @event_post.clicks %>
</p>

<p>
  <strong>User:</strong>
  <%= @event_post.user_id %>
</p>

<p>
  <strong>Division:</strong>
  <%= @event_post.division_id %>
</p>

<%= link_to 'Edit', edit_event_post_path(@event_post) %> |
<%= link_to 'Back', event_posts_path %>